version: "3.9"

services:
  mysql:
    build:
      context: ./mysql
    image: mysql
    container_name: mysql_container
    networks:
      db_network:
        aliases:
          - mysql
    volumes:
      - db_volume:/var/lib/mysql
      - ./mysql/conf/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: testdb
    expose:
      - "5655"
    healthcheck:
      test: ["CMD", "mysql", "-h", "localhost", "-P", "5655", "-uroot", "-proot", "-e", "SELECT 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  app:
    build:
      context: ./app
    image: app
    networks:
      - db_network
      - site_network
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD:
      MYSQL_DATABASE: testdb
    depends_on:
      mysql:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wget --spider -q http://127.0.0.1:4743/health || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
    expose:
      - "4743"

  nginx:
    build:
      context: ./nginx
    image: nginx
    container_name: nginx_container
    ports:
      - "5423:824"
    networks:
      - site_network
    volumes:
      - ./nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      app:
        condition: service_healthy

volumes:
  db_volume:

networks:
  db_network:
  site_network:
